(cl:in-package serial_comms-msg)
(cl:export '(HEADER-VAL
          HEADER
          WEEK-VAL
          WEEK
          SECONDS-VAL
          SECONDS
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          UNDULATION-VAL
          UNDULATION
          STD_LAT-VAL
          STD_LAT
          STD_LON-VAL
          STD_LON
          STD_ALT-VAL
          STD_ALT
          VE-VAL
          VE
          VN-VAL
          VN
          VU-VAL
          VU
          STD_VE-VAL
          STD_VE
          STD_VN-VAL
          STD_VN
          STD_VU-VAL
          STD_VU
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          YAW-VAL
          YAW
          STD_PITCH-VAL
          STD_PITCH
          STD_ROLL-VAL
          STD_ROLL
          STD_YAW-VAL
          STD_YAW
          NS-VAL
          NS
          GNSS_ST-VAL
          GNSS_ST
          NAV_ST-VAL
          NAV_ST
          ODO_ST-VAL
          ODO_ST
          NAV_STATUS-VAL
          NAV_STATUS
))